title: "Awala"
description: "La red más resistente y moderna"
author: "Relaycorp, Inc."
lang: es

twitter_username: LaRedAwala
facebook_username: AwalaNetwork

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
